name: Electron Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger build on version tag push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App
        run: npm run build  # Make sure you have this script in your package.json

      - name: Package Electron App
        run: npm run package  # Ensure you have a packaging script (like electron-builder or electron-forge)

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: 'path_to_your_exe_or_dist_directory/*.exe'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
